### ISSUE TITLE
Error on loading CMakeLists.txt  c++: error: /wd4819: No such file or directory

### ISSUE THREAD

**Issue by shubhamwagh** [dogod621/E57Converter#1]
Problems were encountered while collecting compiler information:
	c++: error: /wd4819: No such file or directory

**Comment by dogod621** [comment]
oh,... remove the wd4819 compile flag in cmakelist, i had only tried to compile the project with visual studio 2017 on win10

**Comment by dogod621** [comment]
@shubhamwagh I had updated the cmakelist~ please try again...

**Comment by shubhamwagh** [comment]
Yes! I actually figured it out after posting it. Thanks now it works.
